AWSTemplateFormatVersion: '2010-09-09'
Description: 'Alert topic'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Alert Parameters'
      Parameters:
        - Email
Parameters:
  Email:
    Description: 'Optional email address that will receive alerts.'
    Type: String
    Default: ''
Resources:
  Topic:
    Type: 'AWS::SNS::Topic'
    Properties: {}
  TopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Id: Id1
        Version: '2012-10-17'
        Statement:
        - Sid: Sid1
          Effect: Allow
          Principal:
            Service:
              - 'events.amazonaws.com' # Allow CloudWatch Events
              - 'budgets.amazonaws.com' # Allow Budget Notifications
              - 'rds.amazonaws.com' # Allow RDS Events
              - 's3.amazonaws.com' # Allow S3 Event Notifications
              - 'backup.amazonaws.com' # Allow Backup Events
              - 'codestar-notifications.amazonaws.com' # Allow CodeStart Notifications
          Action: 'sns:Publish'
          Resource: !Ref Topic
        - Sid: Sid2
          Effect: Allow
          Principal:
            AWS: '*' # Allow CloudWatch Alarms, ElastiCache Notifications, Elastic Beanstalk Notifications, Auto Scaling Notification
          Action: 'sns:Publish'
          Resource: !Ref Topic
          Condition:
            StringEquals:
              'AWS:SourceOwner': !Ref 'AWS::AccountId'
        - Sid: Sid3
          Effect: Allow
          Principal:
            Service: 'ses.amazonaws.com' # Allow SES Notifications & Events
          Action: 'sns:Publish'
          Resource: !Ref Topic
          Condition:
            StringEquals:
              'AWS:Referer': !Ref 'AWS::AccountId'
      Topics:
      - !Ref Topic

  EmailSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !Ref Email
      Protocol: email
      TopicArn: !Ref Topic

Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  TopicARN:
    Description: 'The ARN of the alert topic.'
    Value: !Ref Topic
    Export:
      Name: !Sub '${AWS::StackName}-TopicARN'
  TopicName:
    Description: 'The name of the alert topic.'
    Value: !GetAtt 'Topic.TopicName'
    Export:
      Name: !Sub '${AWS::StackName}-TopicName'
