AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deployment Resources for Static Website'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stacks'
      Parameters:
      - ParentWebsiteStack
Parameters:
  ParentWebsiteStack:
    Type: String

Resources:
  DeployGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: !Sub '${AWS::StackName}-deploy-group'

  DeployPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub '${AWS::StackName}-deploy-policy'
      Groups:
        - !Ref DeployGroup
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: id1
            Effect: 'Allow'
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:DeleteObject'
              - 's3:GetBucketLocation'
              - 's3:PutObjectAcl'
              - 'cloudfront:CreateInvalidation'
            Resource:
              - {'Fn::ImportValue': !Sub '${ParentWebsiteStack}-BucketArn'}
              - !Sub
                - '${Arn}/*'
                - Arn: {'Fn::ImportValue': !Sub '${ParentWebsiteStack}-BucketArn'}
              - !Sub
                - 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistId}'
                - DistId: {'Fn::ImportValue': !Sub '${ParentWebsiteStack}-DistributionId'}

  DeployUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Sub '${AWS::StackName}-deploy-user'
      Groups:
        - !Ref DeployGroup
