AWSTemplateFormatVersion: '2010-09-09'
Description: 'Hosted Zone and a catch all certificate'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Zone Parameters'
      Parameters:
      - Name
Parameters:
  Name:
    Description: 'The name of the domain (hosted zone).'
    Type: String
Resources:
  HostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: !Sub "${Name} public hosted zone"
      Name: !Ref Name

  Certificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Sub '*.${Name}'
      DomainValidationOptions:
        - DomainName: !Sub '*.${Name}'
          HostedZoneId: !Ref HostedZone
      SubjectAlternativeNames:
        - !Ref Name
      ValidationMethod: DNS

Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  HostedZoneName:
    Description: 'The name of the hosted zone.'
    Value: !Ref Name
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneName'
  HostedZoneId:
    Description: 'The ID of the hosted zone.'
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'
  CertificateArn:
    Description: 'The ARN of the Certificate'
    Value: !Ref Certificate
    Export:
      Name: !Sub '${AWS::StackName}-CertificateArn'
