/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_CONVEX_CLOUD_ORIGIN: string
  readonly VITE_CONVEX_SITE_ORIGIN: string
  readonly VITE_CONVEX_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}